/**
 * Branded Trust Report PDF renderer (shared port of #57).
 *
 * A narrow, self-contained subset of the web PDF generator, ported here
 * to keep the shared library framework-agnostic. Only supports the
 * sections the trust-report actually needs: summary cards, tables, text
 * paragraphs, spacers.
 *
 * The full `lib/reports/pdf-generator.ts` in the web app stays put for
 * other report flows (entitlements, access matrix exports, etc.).
 *
 * PAYLOAD HYGIENE — the assembler never produces credentials, tokens, or
 * full directory rows, so this renderer only has to render what it is
 * given. It must not re-fetch or enrich beyond the payload.
 */

import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import type { PDFPage, PDFFont, Color } from 'pdf-lib';
import type { TrustReportPayload } from './assembler.js';

// ── Types ─────────────────────────────────────────────────────────────

interface SummaryItem {
  label: string;
  value: string | number;
}

interface SummarySection {
  type: 'summary';
  title?: string;
  items: SummaryItem[];
}

interface TableSection {
  type: 'table';
  title?: string;
  headers: string[];
  rows: string[][];
}

interface TextSection {
  type: 'text';
  content: string;
  bold?: boolean;
}

interface SpacerSection {
  type: 'spacer';
  height?: number;
}

type PdfSection = SummarySection | TableSection | TextSection | SpacerSection;

interface PdfReportOptions {
  title?: string;
  subtitle?: string;
  agencyName?: string;
  generatedAt?: string;
  sections?: PdfSection[];
  footer?: string;
}

export interface BrandedPdfResult {
  bytes: Uint8Array;
  coverAppliedBranding: boolean;
  primaryColor: string;
}

// ── Public entrypoint ─────────────────────────────────────────────────

const GENERIC_COVER_TITLE = 'Quarterly Trust Report';
const GENERIC_COVER_SUBTITLE = 'Access Hive — Identity Governance Report';
const GENERIC_PRIMARY_COLOR = '#465fff';

export async function renderTrustReportPdf(
  payload: TrustReportPayload,
): Promise<BrandedPdfResult> {
  const branded = Boolean(payload.branding?.logoUrl || payload.branding?.primaryColor);
  const primaryColor = sanitizeColor(payload.branding?.primaryColor) || GENERIC_PRIMARY_COLOR;
  const coverTitle =
    payload.branding?.coverTitle ||
    (branded ? `${payload.clientName} — Trust Report` : GENERIC_COVER_TITLE);
  const subtitle = `${payload.quarter.label} (${payload.quarter.startDate} to ${payload.quarter.endDate})`;

  const sections: PdfSection[] = [
    {
      type: 'text',
      content: branded
        ? `Prepared for ${payload.clientName}.`
        : GENERIC_COVER_SUBTITLE,
      bold: true,
    },
    { type: 'spacer', height: 8 },
    {
      type: 'summary',
      title: 'Overview',
      items: payload.summary.map((s) => ({ label: s.label, value: String(s.value) })),
    },
    { type: 'spacer', height: 10 },
    renderTable(payload.accessMatrix),
    { type: 'spacer', height: 10 },
    renderTable(payload.staleAccess),
    { type: 'spacer', height: 10 },
    renderTable(payload.driftSummary),
    { type: 'spacer', height: 10 },
    {
      type: 'text',
      content:
        'This report contains only aggregate access metadata (user name, email, role, platform). ' +
        'No credentials, tokens, or raw directory records are included.',
    },
  ];

  const bytes = await generatePdf({
    title: coverTitle,
    subtitle,
    agencyName: payload.agencySlug || '',
    generatedAt: new Date().toISOString(),
    sections,
    footer: branded
      ? `${payload.clientName} — Confidential Trust Report`
      : 'Access Hive — Confidential Trust Report',
  });

  return { bytes, coverAppliedBranding: branded, primaryColor };
}

function renderTable(section: {
  title: string;
  headers: string[];
  rows: string[][];
  note?: string;
}): PdfSection {
  return {
    type: 'table',
    title: section.title + (section.note ? ` — ${section.note}` : ''),
    headers: section.headers,
    rows: section.rows.length > 0 ? section.rows : [section.headers.map(() => '—')],
  };
}

function sanitizeColor(input?: string | null): string | null {
  if (!input) return null;
  const s = input.trim();
  return /^#[0-9a-fA-F]{6}$/.test(s) ? s : null;
}

// ── Core PDF generator (narrow port from lib/reports/pdf-generator.ts) ──

async function generatePdf(options: PdfReportOptions): Promise<Uint8Array> {
  const {
    title = 'Report',
    subtitle = '',
    agencyName = '',
    generatedAt = new Date().toISOString(),
    sections = [],
    footer = 'Generated by AccessHive \u2014 Confidential',
  } = options;

  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const brandColor: Color = rgb(70 / 255, 95 / 255, 255 / 255);
  const textColor: Color = rgb(31 / 255, 41 / 255, 55 / 255);
  const mutedColor: Color = rgb(107 / 255, 114 / 255, 128 / 255);
  const headerBg: Color = rgb(249 / 255, 250 / 255, 251 / 255);
  const altRowBg: Color = rgb(249 / 255, 250 / 255, 251 / 255);
  const borderColor: Color = rgb(229 / 255, 231 / 255, 235 / 255);
  const white: Color = rgb(1, 1, 1);

  const PAGE_WIDTH = 612; // US Letter
  const PAGE_HEIGHT = 792;
  const MARGIN_LEFT = 50;
  const MARGIN_RIGHT = 50;
  const MARGIN_TOP = 50;
  const MARGIN_BOTTOM = 60;
  const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT;
  const FOOTER_Y = 30;

  let currentPage: PDFPage = null!;
  let y = 0;
  let pageNumber = 0;
  const pages: PDFPage[] = [];

  function addPage(): PDFPage {
    currentPage = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    pageNumber++;
    pages.push(currentPage);
    y = PAGE_HEIGHT - MARGIN_TOP;
    return currentPage;
  }

  function ensureSpace(needed: number): void {
    if (y - needed < MARGIN_BOTTOM) {
      addPage();
    }
  }

  function drawFooter(page: PDFPage, num: number): void {
    const footerText = footer;
    const pageText = `Page ${num}`;
    page.drawText(footerText, {
      x: MARGIN_LEFT,
      y: FOOTER_Y,
      size: 8,
      font,
      color: mutedColor,
    });
    const pageTextWidth = font.widthOfTextAtSize(pageText, 8);
    page.drawText(pageText, {
      x: PAGE_WIDTH - MARGIN_RIGHT - pageTextWidth,
      y: FOOTER_Y,
      size: 8,
      font,
      color: mutedColor,
    });
  }

  function truncateText(text: string | null | undefined, maxWidth: number, f: PDFFont, size: number): string {
    if (!text) return '';
    let str = String(text);
    if (f.widthOfTextAtSize(str, size) <= maxWidth) return str;
    while (str.length > 0 && f.widthOfTextAtSize(str + '...', size) > maxWidth) {
      str = str.slice(0, -1);
    }
    return str + '...';
  }

  function wrapText(text: string | null | undefined, maxWidth: number, f: PDFFont, size: number): string[] {
    if (!text) return [''];
    const words = String(text).split(/\s+/);
    const lines: string[] = [];
    let currentLine = '';

    for (const word of words) {
      const testLine = currentLine ? `${currentLine} ${word}` : word;
      if (f.widthOfTextAtSize(testLine, size) <= maxWidth) {
        currentLine = testLine;
      } else {
        if (currentLine) lines.push(currentLine);
        currentLine = word;
      }
    }
    if (currentLine) lines.push(currentLine);
    return lines.length > 0 ? lines : [''];
  }

  addPage();

  // ── Header (title bar) ──────────────────────────────────────────────
  currentPage.drawRectangle({
    x: MARGIN_LEFT,
    y: y - 40,
    width: CONTENT_WIDTH,
    height: 45,
    color: brandColor,
  });

  currentPage.drawText(title, {
    x: MARGIN_LEFT + 12,
    y: y - 28,
    size: 18,
    font: fontBold,
    color: white,
  });

  y -= 55;

  if (subtitle || agencyName) {
    const metaLine = [agencyName, subtitle].filter(Boolean).join(' \u2014 ');
    currentPage.drawText(metaLine, {
      x: MARGIN_LEFT,
      y,
      size: 10,
      font,
      color: mutedColor,
    });
    y -= 14;
  }

  const formattedDate = formatDate(generatedAt);
  currentPage.drawText(`Generated: ${formattedDate}`, {
    x: MARGIN_LEFT,
    y,
    size: 8,
    font,
    color: mutedColor,
  });
  y -= 8;

  currentPage.drawLine({
    start: { x: MARGIN_LEFT, y },
    end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
    thickness: 1,
    color: borderColor,
  });
  y -= 20;

  // ── Section dispatch ────────────────────────────────────────────────
  for (const section of sections) {
    switch (section.type) {
      case 'summary':
        renderSummary(section);
        break;
      case 'table':
        renderTableSection(section);
        break;
      case 'text':
        renderText(section);
        break;
      case 'spacer':
        y -= section.height || 20;
        if (y < MARGIN_BOTTOM) addPage();
        break;
      default:
        break;
    }
  }

  for (let i = 0; i < pages.length; i++) {
    drawFooter(pages[i], i + 1);
  }

  return pdfDoc.save();

  // ── Section renderers ───────────────────────────────────────────────

  function renderSummary(section: SummarySection): void {
    const items = section.items || [];
    if (items.length === 0) return;

    if (section.title) {
      ensureSpace(30);
      currentPage.drawText(section.title, {
        x: MARGIN_LEFT,
        y,
        size: 12,
        font: fontBold,
        color: textColor,
      });
      y -= 18;
    }

    const colWidth = CONTENT_WIDTH / 2;
    const itemHeight = 36;
    const padding = 8;

    for (let i = 0; i < items.length; i += 2) {
      ensureSpace(itemHeight + 8);

      for (let col = 0; col < 2 && i + col < items.length; col++) {
        const item = items[i + col];
        const x = MARGIN_LEFT + col * colWidth;

        currentPage.drawRectangle({
          x: x + 2,
          y: y - itemHeight + 4,
          width: colWidth - 8,
          height: itemHeight,
          color: headerBg,
          borderColor,
          borderWidth: 0.5,
        });

        currentPage.drawText(String(item.label || ''), {
          x: x + padding + 2,
          y: y - 10,
          size: 7,
          font,
          color: mutedColor,
        });

        const valueText = truncateText(String(item.value ?? ''), colWidth - padding * 2 - 8, fontBold, 11);
        currentPage.drawText(valueText, {
          x: x + padding + 2,
          y: y - 24,
          size: 11,
          font: fontBold,
          color: textColor,
        });
      }

      y -= itemHeight + 6;
    }

    y -= 10;
  }

  function renderTableSection(section: TableSection): void {
    const headers = section.headers || [];
    const rows = section.rows || [];
    if (headers.length === 0) return;

    if (section.title) {
      ensureSpace(30);
      currentPage.drawText(section.title, {
        x: MARGIN_LEFT,
        y,
        size: 12,
        font: fontBold,
        color: textColor,
      });
      y -= 18;
    }

    const colWidths = computeColumnWidths(headers, rows, font, fontBold);
    const rowHeight = 18;
    const cellPadding = 6;

    ensureSpace(rowHeight + 4);
    currentPage.drawRectangle({
      x: MARGIN_LEFT,
      y: y - rowHeight,
      width: CONTENT_WIDTH,
      height: rowHeight,
      color: headerBg,
    });

    let xOffset = MARGIN_LEFT;
    for (let i = 0; i < headers.length; i++) {
      const text = truncateText(String(headers[i] || ''), colWidths[i] - cellPadding * 2, fontBold, 8);
      currentPage.drawText(text, {
        x: xOffset + cellPadding,
        y: y - 12,
        size: 8,
        font: fontBold,
        color: mutedColor,
      });
      xOffset += colWidths[i];
    }
    y -= rowHeight;

    currentPage.drawLine({
      start: { x: MARGIN_LEFT, y },
      end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
      thickness: 0.5,
      color: borderColor,
    });

    for (let rowIdx = 0; rowIdx < rows.length; rowIdx++) {
      const row = rows[rowIdx];
      ensureSpace(rowHeight + 2);

      if (rowIdx % 2 === 1) {
        currentPage.drawRectangle({
          x: MARGIN_LEFT,
          y: y - rowHeight,
          width: CONTENT_WIDTH,
          height: rowHeight,
          color: altRowBg,
        });
      }

      xOffset = MARGIN_LEFT;
      for (let i = 0; i < headers.length; i++) {
        const cellText = truncateText(String(row[i] ?? ''), colWidths[i] - cellPadding * 2, font, 8);
        currentPage.drawText(cellText, {
          x: xOffset + cellPadding,
          y: y - 12,
          size: 8,
          font,
          color: textColor,
        });
        xOffset += colWidths[i];
      }

      y -= rowHeight;

      currentPage.drawLine({
        start: { x: MARGIN_LEFT, y },
        end: { x: PAGE_WIDTH - MARGIN_RIGHT, y },
        thickness: 0.25,
        color: borderColor,
      });
    }

    y -= 14;
  }

  function renderText(section: TextSection): void {
    const content = section.content || '';
    const isBold = section.bold || false;
    const f = isBold ? fontBold : font;
    const size = isBold ? 11 : 9;

    const lines = wrapText(content, CONTENT_WIDTH, f, size);
    for (const line of lines) {
      ensureSpace(14);
      currentPage.drawText(line, {
        x: MARGIN_LEFT,
        y,
        size,
        font: f,
        color: textColor,
      });
      y -= size + 4;
    }
    y -= 6;
  }

  function computeColumnWidths(headers: string[], rows: string[][], f: PDFFont, fb: PDFFont): number[] {
    const widths = headers.map((h) => fb.widthOfTextAtSize(String(h || ''), 8) + 16);

    const sampleRows = rows.slice(0, 20);
    for (const row of sampleRows) {
      for (let i = 0; i < headers.length; i++) {
        const cellWidth = f.widthOfTextAtSize(String(row[i] ?? ''), 8) + 16;
        widths[i] = Math.max(widths[i], cellWidth);
      }
    }

    const totalWidth = widths.reduce((s, w) => s + w, 0);
    if (totalWidth > 0) {
      const scale = CONTENT_WIDTH / totalWidth;
      return widths.map((w) => w * scale);
    }

    return headers.map(() => CONTENT_WIDTH / headers.length);
  }
}

function formatDate(iso: string): string {
  if (!iso) return '-';
  try {
    return new Date(iso).toLocaleString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
      timeZoneName: 'short',
    });
  } catch {
    return iso;
  }
}
