/**
 * Synthetic event used by every plugin's test() entrypoint.
 *
 * The contents intentionally mirror the shape of a real audit event so a
 * destination can validate end-to-end formatting + transport with one click.
 */

import type { AuditEvent } from './audit-destination-plugin.interface.js';

export function buildTestEvent(agencyId: string): AuditEvent {
  return {
    eventId: `test-${Date.now()}`,
    timestamp: new Date().toISOString(),
    eventType: 'audit.test.fired',
    severity: 'info',
    source: 'accesshive',
    actor: {
      id: 'system',
      email: 'system@accesshive.io',
      name: 'AccessHive Test',
      type: 'system',
    },
    agency: { id: agencyId },
    resource: { type: 'destination', name: 'Test connection' },
    context: { test: true, note: 'This event was generated by Audit Settings → Test connection.' },
  };
}
